name: Simple-GitHub-Actions-For-Flask-App

env:
  APPLICATION_NAME: "SimpleFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Msg
        run: echo "Starting tests..."
      - name: Execute commands
        run: |
          echo "Install dependencies..."
          echo "Run tests..."
          echo "${{ env.APPLICATION_NAME }} is tested!!!"


  deploy:
    runs-on: ubuntu-latest

    needs: [testing]

    steps:
      - name: Print Start Msg
        run: echo "Starting deploy..."
      - name: Deploy
        run: |
          echo "Deploying"
          echo "${{ env.DEPLOY_PACKAGE_NAME }} is deployed"
