name: Testing-Flask-App

env:
  APPLICATION_NAME          : "SimpleFlask"

on:
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Msg
        run : echo "Starting tests..."

      - name: Get repo
        uses: actions/checkout@v1

      - name: Execute commands
        env :
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run : |
          echo "Install dependencies..."
          pip3 --version
          pip3 install -r requirements.txt
          pip3 install git+https://miktuy:${{ secrets.GIT_WORD }}@github.com/miktuy/simple-page-objects.git
          export FLASK_APP=application.py
          python3 application.py &
          sleep 10
          echo "Run tests..."
          python3 -m robot -L trace -P . tests/robot_tests/Smoke.robot
          echo "${{ env.APPLICATION_NAME }} is tested!!!"