name: Testing-Flask-App

env:
  APPLICATION_NAME          : "SimpleFlask"

on:
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Msg
        run : echo "Starting tests..."

      - name: Get repo
        uses: actions/checkout@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GIT_HUB_SIMPLE_PO_RSA_KEY }}
          name: id_rsa_simple_key
          known_hosts: github.com

      - name: Execute commands
        run : |
          echo "Install dependencies..."
          pip3 --version
          pip3 install -r requirements.txt
          export FLASK_APP=application.py
          python3 application.py &
          sleep 10
          pip3 install -r tests/requirements.txt
          echo "Run tests..."
          python3 -m robot -L trace -P . tests/robot_tests/Smoke.robot
          echo "${{ env.APPLICATION_NAME }} is tested!!!"