name: Testing-Flask-App

env:
  APPLICATION_NAME          : "SimpleFlask"

on:
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start Msg
        run : echo "Starting tests..."

      - name: Get repo
        uses: actions/checkout@v1

      - name           : Setup SSH Keys and known_hosts
        env            :
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY      : ${{ secrets.GIT_HUB_SIMPLE_PO_RSA_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< $SSH_KEY

      - name: Execute commands
        env :
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run : |
          echo "Install dependencies..."
          pip3 --version
          pip3 install -r requirements.txt
          export FLASK_APP=application.py
          python3 application.py &
          sleep 10
          echo "Run tests..."
          pip3 install -r ./tests/requirements.txt
          python3 -m robot -L trace -P . tests/robot_tests/Smoke.robot
          echo "${{ env.APPLICATION_NAME }} is tested!!!"